/* Differential test: reconstructed pcalc.o against the 1998 object.
 *
 * PCalc's input is a whole Pre3 object, and its behaviour depends on that
 * object being self-consistent (the edge deltas, the signed area and the
 * vertex queue all have to agree), so the drive stream is generated by the
 * *original* pre1.o + pre3.o: random register writes go into Pre1::Put,
 * Pre3 forwards to a fake PCalc whose single vtable entry snapshots the
 * Pre3 object, and every snapshot is then replayed into both PCalcs.
 *
 * Both PCalcs get their own copy of the snapshot because PCalc::DrawTriangle
 * negates Pre3::area in place.  Each PCalc also gets its own param/div/slong
 * cluster (the 1998 objects for the old side, the reconstruction for the new
 * one), so the whole call graph below PCalc is exercised too.
 *
 * Compared after every Put: the complete 0xc00-byte PCalc object (minus the
 * three pointer fields that legitimately differ), the mutated Pre3 copy, and
 * the PCalc image captured at every downstream (PPOut) Put.
 *
 * Built by test/run_pcalc.sh, which renames the 1998 symbols to o_* and the
 * reconstructed ones to n_* first.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* glibc 2.0 exported the stderr FILE object itself as _IO_stderr_; the only
   reference to it is Pre1::MaxExp()'s "illegal primitive type" exit. */
char _IO_stderr_[1024];

#define PRE1_SIZE	0xac
#define PRE3_SIZE	0x14c
#define PRE3_VPTR	0x148
#define PCALC_SIZE	0xc00
#define PCALC_VPTR	0xbfc
#define PCALC_OUT	0x000		/* PPDDA* */
#define PCALC_RCP	0x104		/* Reciproc: two heap pointers */

/* g++ 2.7 non-thunk vtable: 8 zero bytes, then {short delta; short pad; fn} */
struct vtable {
	int zero0, zero1;
	short delta;
	short pad;
	void (*fn)(void *self, void *arg);
};

/* ---- libgcc / g++ runtime bits the 1998 objects call ------------------ */

static unsigned long long
udiv64(unsigned long long a, unsigned long long b)
{
	unsigned long long q = 0, r = 0;
	int i;

	for (i = 63; i >= 0; i--) {
		r = (r << 1) | ((a >> i) & 1);
		if (r >= b) {
			r -= b;
			q |= 1ULL << i;
		}
	}
	return q;
}

long long
__divdi3(long long a, long long b)
{
	unsigned long long ua, ub, q;
	int neg = 0;

	if (a < 0) { ua = -(unsigned long long)a; neg ^= 1; } else ua = a;
	if (b < 0) { ub = -(unsigned long long)b; neg ^= 1; } else ub = b;
	q = udiv64(ua, ub);
	return neg ? -(long long)q : (long long)q;
}

void *
__builtin_vec_new(unsigned int n)
{
	void *p = malloc(n);

	if (p == 0) {
		printf("out of memory\n");
		exit(1);
	}
	return p;
}

/* ---- the two sides ---------------------------------------------------- */

extern void *o_pcalc_ctor(void *pcalc, void *out);
extern void o_pcalc_put(void *pcalc, void *pre3);
extern void *n_pcalc_ctor(void *pcalc, void *out);
extern void n_pcalc_put(void *pcalc, void *pre3);

/* the driver: the 1998 front end */
extern void *__4Pre1P4Pre3(void *pre1, void *pre3);
extern void *__4Pre3P5PCalc(void *pre3, void *pcalc);
extern void Put__4Pre1ix(void *pre1, int addr, long long data);
extern char _vt_4Pre3[];		/* renamed _vt.4Pre3 */

/* ---- Pre3 capture (the drive stream) ---------------------------------- */

#define MAXPRE3	64
static unsigned char pre3cap[MAXPRE3][PRE3_SIZE];
static int npre3;

static void
grab_pre3(void *pcalc, void *pre3)
{
	(void)pcalc;
	if (npre3 < MAXPRE3)
		memcpy(pre3cap[npre3], pre3, PRE3_SIZE);
	npre3++;
}

/* ---- downstream capture ----------------------------------------------- */

#define MAXOUT	8
static unsigned char outcap[2][MAXOUT][PCALC_SIZE];
static int nout[2];
static int side;

static void
grab_out(void *ppdda, void *pcalc)
{
	(void)ppdda;
	if (nout[side] < MAXOUT)
		memcpy(outcap[side][nout[side]], pcalc, PCALC_SIZE);
	nout[side]++;
}

static struct vtable pre3_vt;		/* the fake PCalc under Pre3 */
static struct vtable out_vt;		/* the fake PPDDA under PCalc */

struct ppdda {
	struct vtable *vt;
	void *dda;
};

/* Offsets whose contents legitimately differ between the two instances. */
static int
skipoff(int k)
{
	return k == PCALC_OUT || k == PCALC_RCP || k == PCALC_RCP + 4 ||
		k == PCALC_VPTR;
}

static int
cmp_pcalc(const void *a, const void *b)
{
	const unsigned char *x = a, *y = b;
	int k;

	for (k = 0; k < PCALC_SIZE; k += 4)
		if (!skipoff(k) && memcmp(x + k, y + k, 4) != 0)
			return 1;
	return 0;
}

static void
show_pcalc(const void *a, const void *b)
{
	const unsigned char *x = a, *y = b;
	int k, n = 0;

	for (k = 0; k < PCALC_SIZE; k += 4)
		if (!skipoff(k) && memcmp(x + k, y + k, 4) != 0) {
			printf("   PCalc+%#05x: %08x vs %08x\n", k,
				*(unsigned *)(x + k), *(unsigned *)(y + k));
			if (++n > 24) {
				printf("   ...\n");
				return;
			}
		}
}

static unsigned int seed = 987654321;

static unsigned int
rnd(void)
{
	seed = seed * 1103515245 + 12345;
	return seed >> 8;
}

int
main(int argc, char **argv)
{
	void *pre1, *pre3, *dummy;
	void *opc, *npc;
	static struct ppdda oout, nout_obj;
	static unsigned char osnap[PRE3_SIZE], nsnap[PRE3_SIZE];
	long iter, n;
	int i, j, k, bad = 0;
	long puts = 0, states = 0, outs = 0;
	int addr;
	long long data;
	static const int regs[] = {
		0x01, 0x02, 0x03, 0x04, 0x05, 0x0a, 0x0c, 0x0d,
		0x11, 0x12, 0x13, 0x18, 0x19, 0x1a, 0x1b,
		0x22, 0x40, 0x41, 0x47, 0x1c
	};

	n = argc > 1 ? atol(argv[1]) : 2000000;

	pre3_vt.fn = grab_pre3;
	out_vt.fn = grab_out;
	oout.vt = &out_vt;
	nout_obj.vt = &out_vt;

	/* the driver front end, with a stub PCalc that only captures */
	dummy = calloc(1, PCALC_SIZE);
	*(void **)((char *)dummy + PCALC_VPTR) = &pre3_vt;
	pre3 = calloc(1, PRE3_SIZE);
	__4Pre3P5PCalc(pre3, dummy);
	*(void **)((char *)pre3 + PRE3_VPTR) = _vt_4Pre3;
	pre1 = calloc(1, PRE1_SIZE);
	__4Pre1P4Pre3(pre1, pre3);

	/* the two PCalcs under test */
	opc = calloc(1, PCALC_SIZE);
	npc = calloc(1, PCALC_SIZE);
	o_pcalc_ctor(opc, &oout);
	n_pcalc_ctor(npc, &nout_obj);
	if (cmp_pcalc(opc, npc) != 0) {
		printf("FAIL: constructors differ\n");
		show_pcalc(opc, npc);
		bad++;
	}

	for (iter = 0; iter < n; iter++) {
		if ((iter & 15) == 0) {
			addr = 0x00;
			data = rnd() % 7;			/* PRIM */
			data |= (long long)(rnd() & 0x7ff) << 3;	/* flags */
		} else if ((iter & 255) == 7) {
			addr = 0x40 + (rnd() & 1);		/* SCISSOR */
			data = ((long long)(rnd() & 0x7ff) << 32) |
				((long long)(rnd() & 0x7ff) << 48) |
				(rnd() & 0x7ff) | ((rnd() & 0x7ff) << 16);
		} else if ((iter & 255) == 23) {
			addr = 0x22;				/* SCANMSK */
			data = rnd() & 3;
		} else if ((iter & 63) == 11) {
			addr = regs[rnd() % (sizeof regs / sizeof regs[0])];
			data = ((long long)rnd() << 32) ^ rnd();
		} else {
			addr = regs[rnd() % (sizeof regs / sizeof regs[0])];
			/* keep coordinates in a plausible screen range most of
			   the time, but go wild sometimes */
			if (rnd() & 3)
				data = (long long)(rnd() % 0x4000) |
					((long long)(rnd() % 0x4000) << 16) |
					((long long)(rnd() & 0xffffff) << 32);
			else
				data = ((long long)rnd() << 32) ^
					((long long)rnd() << 11) ^ rnd();
		}

		npre3 = 0;
		Put__4Pre1ix(pre1, addr, data);

		for (i = 0; i < npre3 && i < MAXPRE3; i++) {
			memcpy(osnap, pre3cap[i], PRE3_SIZE);
			memcpy(nsnap, pre3cap[i], PRE3_SIZE);
			/* Pre3+0x120 is never set by pre3.o, but PCalc has
			   whole code paths keyed on it; drive it here. */
			if ((rnd() & 7) == 0) {
				*(int *)(osnap + 0x120) = 1;
				*(int *)(nsnap + 0x120) = 1;
			}
			nout[0] = nout[1] = 0;
			side = 0;
			o_pcalc_put(opc, osnap);
			side = 1;
			n_pcalc_put(npc, nsnap);
			puts++;

			if (nout[0] != nout[1]) {
				printf("FAIL %ld: %d vs %d downstream Puts\n",
					iter, nout[0], nout[1]);
				if (++bad > 10)
					goto done;
				continue;
			}
			for (j = 0; j < nout[0] && j < MAXOUT; j++) {
				outs++;
				if (cmp_pcalc(outcap[0][j], outcap[1][j]) == 0)
					continue;
				printf("FAIL %ld: downstream Put %d differs "
					"(type %d, send_type %d)\n", iter, j,
					*(int *)(outcap[0][j] + 0xbf8),
					*(int *)(outcap[0][j] + 0xbb4));
				show_pcalc(outcap[0][j], outcap[1][j]);
				if (++bad > 10)
					goto done;
			}
			if (memcmp(osnap, nsnap, PRE3_VPTR) != 0) {
				printf("FAIL %ld: Pre3 mutated differently\n",
					iter);
				for (k = 0; k < PRE3_VPTR; k += 4)
					if (memcmp(osnap + k, nsnap + k, 4))
						printf("   Pre3+%#05x: %08x vs "
							"%08x\n", k,
							*(unsigned *)(osnap + k),
							*(unsigned *)(nsnap + k));
				if (++bad > 10)
					goto done;
			}
			states++;
			if (cmp_pcalc(opc, npc) != 0) {
				printf("FAIL %ld: PCalc state diverged\n", iter);
				show_pcalc(opc, npc);
				if (++bad > 10)
					goto done;
			}
		}
	}
done:
	printf("%ld register writes, %ld PCalc::Put calls, %ld downstream "
		"Puts, %ld state checks, %d failures\n",
		iter, puts, outs, states, bad);
	return bad != 0;
}
